image: eeacms/rsync

pages:
  tags:
    - shared
  stage: deploy
  script:
    - mkdir .public
    - rsync -r --exclude=gitlab-ci.yml * .public
    - mv .public public

  artifacts:
    paths:
      - public
  only:
    - pages
