name: 'Install node dependencies'
description: 'Installs the node dependencies of inovex-elements packages'
author: 'Benjamin Pagelsdorf'
inputs:
  skip-browsers:
    description: 'Skip Playwright browser downloads'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.29.2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org
        scope: '@inovex.de'
        always-auth: true
        cache: 'pnpm'

    - name: Restore Turborepo Cache
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          node_modules/.cache/turbo
        key: turbo-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}-${{ github.ref_name }}-
          turbo-${{ runner.os }}-

    - name: Skip browser downloads
      if: inputs.skip-browsers == 'true'
      run: |
        echo "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1" >> $GITHUB_ENV
      shell: bash

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
