import type { NextPage } from 'next';
import Head from 'next/head';
import RandomTextBlock from './randomTextBlock';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <RandomTextBlock />
      </main>
    </div>
  );
};

export default Home;
