
        export type IconMap = {
          '_fab_set_arrow_down': string;
  '_fab_set_arrow_up': string;
  '_input_number_arrow_down': string;
  '_input_number_arrow_up': string;
  'add': string;
  'arrow_down': string;
  'arrow_left': string;
  'arrow_right': string;
  'arrow_up': string;
  'back_arrow': string;
  'birthday': string;
  'bold': string;
  'bullet_list': string;
  'calendar': string;
  'call': string;
  'camera': string;
  'cart': string;
  'chat': string;
  'checkmark': string;
  'close': string;
  'cloud': string;
  'code': string;
  'code_block': string;
  'company': string;
  'copy': string;
  'developer': string;
  'display': string;
  'download': string;
  'edit': string;
  'edit_text': string;
  'employee': string;
  'favorite': string;
  'filter': string;
  'folder': string;
  'headline_one': string;
  'headline_two': string;
  'help': string;
  'image_not_available': string;
  'info': string;
  'italic': string;
  'link': string;
  'location': string;
  'logout': string;
  'mail': string;
  'menu': string;
  'message': string;
  'number': string;
  'numeric_list': string;
  'offboarding': string;
  'offboarding_running': string;
  'onboarding': string;
  'onboarding_running': string;
  'opportunity': string;
  'options': string;
  'options_dotted': string;
  'partner': string;
  'password': string;
  'phone': string;
  'pin': string;
  'print': string;
  'question': string;
  'quote': string;
  'refresh': string;
  'remove': string;
  'report': string;
  'save': string;
  'search': string;
  'settings': string;
  'share': string;
  'snackbar-checkmark': string;
  'snackbar-error': string;
  'snackbar-information': string;
  'sort': string;
  'sort_az': string;
  'sort_down': string;
  'sort_up': string;
  'sort_za': string;
  'star': string;
  'status_away': string;
  'status_current': string;
  'status_future': string;
  'status_past': string;
  'strikethrough': string;
  'time': string;
  'underline': string;
  'upload': string;
  'user': string;
  'warning': string;
  'web': string;
        };
        export type IconNames = keyof IconMap;
        export declare const ICON_PATHS: IconMap;
        export declare const _fabSetArrowDown: string;
export declare const _fabSetArrowUp: string;
export declare const _inputNumberArrowDown: string;
export declare const _inputNumberArrowUp: string;
export declare const add: string;
export declare const arrowDown: string;
export declare const arrowLeft: string;
export declare const arrowRight: string;
export declare const arrowUp: string;
export declare const backArrow: string;
export declare const birthday: string;
export declare const bold: string;
export declare const bulletList: string;
export declare const calendar: string;
export declare const call: string;
export declare const camera: string;
export declare const cart: string;
export declare const chat: string;
export declare const checkmark: string;
export declare const close: string;
export declare const cloud: string;
export declare const code: string;
export declare const codeBlock: string;
export declare const company: string;
export declare const copy: string;
export declare const developer: string;
export declare const display: string;
export declare const download: string;
export declare const edit: string;
export declare const editText: string;
export declare const employee: string;
export declare const favorite: string;
export declare const filter: string;
export declare const folder: string;
export declare const headlineOne: string;
export declare const headlineTwo: string;
export declare const help: string;
export declare const imageNotAvailable: string;
export declare const info: string;
export declare const italic: string;
export declare const link: string;
export declare const location: string;
export declare const logout: string;
export declare const mail: string;
export declare const menu: string;
export declare const message: string;
export declare const number: string;
export declare const numericList: string;
export declare const offboarding: string;
export declare const offboardingRunning: string;
export declare const onboarding: string;
export declare const onboardingRunning: string;
export declare const opportunity: string;
export declare const options: string;
export declare const optionsDotted: string;
export declare const partner: string;
export declare const password: string;
export declare const phone: string;
export declare const pin: string;
export declare const print: string;
export declare const question: string;
export declare const quote: string;
export declare const refresh: string;
export declare const remove: string;
export declare const report: string;
export declare const save: string;
export declare const search: string;
export declare const settings: string;
export declare const share: string;
export declare const snackbarCheckmark: string;
export declare const snackbarError: string;
export declare const snackbarInformation: string;
export declare const sort: string;
export declare const sortAz: string;
export declare const sortDown: string;
export declare const sortUp: string;
export declare const sortZa: string;
export declare const star: string;
export declare const statusAway: string;
export declare const statusCurrent: string;
export declare const statusFuture: string;
export declare const statusPast: string;
export declare const strikethrough: string;
export declare const time: string;
export declare const underline: string;
export declare const upload: string;
export declare const user: string;
export declare const warning: string;
export declare const web: string;
        