name: 'Download elements build artifacts'
description: 'Download elements build artifacts that can be used by release workflows'
author: 'Benjamin Pagelsdorf'

inputs:
  workflow-id:
    description: 'ID of workflow to download artifacts from'
    required: false
  workflow-conclusion:
    description: 'The status or conclusion of a completed workflow to search for'
    required: false
    default: 'success'
  check-artifacts:
    description: 'Check the workflow run to whether it has an artifact'
    required: false
    default: 'false'
  download-core-artifacts:
    description: 'Download core artifacts?'
    required: false
    default: 'false'
  core-artifacts-base-path:
    description: 'Base path of artifact download. Will be suffixed with specific framework name e.g /elements-vue/dist/'
    required: false
    default: 'packages'
  download-example-artifacts:
    description: 'Download example project artifacts?'
    required: false
    default: 'false'
  example-artifacts-base-path:
    description: 'Base path of artifact download. Will be suffixed with specific framework name e.g /vue'
    required: false
    default: 'example-projects'

runs:
  using: "composite"
  steps:
    - if: inputs.download-core-artifacts != 'false'
      name: Download elements artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow-id }}
        name: elements
        path: ${{ inputs.core-artifacts-base-path }}/elements/dist/
        check_artifacts: ${{ inputs.check-artifacts }}
        workflow_conclusion: ${{ inputs.workflow-conclusion }}

    - if: inputs.download-core-artifacts != 'false'
      name: Download elements-react artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow-id }}
        name: elements-react
        path: ${{ inputs.core-artifacts-base-path }}/elements-react/dist/
        check_artifacts: ${{ inputs.check-artifacts }}
        workflow_conclusion: ${{ inputs.workflow-conclusion }}

    - if: inputs.download-core-artifacts != 'false'
      name: Download elements-angular artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow-id }}
        name: elements-angular
        path: ${{ inputs.core-artifacts-base-path }}/elements-angular/elements/dist/
        check_artifacts: ${{ inputs.check-artifacts }}
        workflow_conclusion: ${{ inputs.workflow-conclusion }}

    - if: inputs.download-core-artifacts != 'false'
      name: Download elements-vue artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow-id }}
        name: elements-vue
        path: ${{ inputs.core-artifacts-base-path }}/elements-vue/dist/
        check_artifacts: ${{ inputs.check-artifacts }}
        workflow_conclusion: ${{ inputs.workflow-conclusion }}

    - if: inputs.download-example-artifacts != 'false'
      name: Download elements-angular-example artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow-id }}
        name: elements-angular-example
        path: ${{ inputs.example-artifacts-base-path }}/angular
        check_artifacts: ${{ inputs.check-artifacts }}
        workflow_conclusion: ${{ inputs.workflow-conclusion }}

    - if: inputs.download-example-artifacts != 'false'
      name: Download elements-react-example artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow-id }}
        name: elements-react-example
        path: ${{ inputs.example-artifacts-base-path }}/react
        check_artifacts: ${{ inputs.check-artifacts }}
        workflow_conclusion: ${{ inputs.workflow-conclusion }}

    - if: inputs.download-example-artifacts != 'false'
      name: Download elements-vue-example artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow-id }}
        name: elements-vue-example
        path: ${{ inputs.example-artifacts-base-path }}/vue
        check_artifacts: ${{ inputs.check-artifacts }}
        workflow_conclusion: ${{ inputs.workflow-conclusion }}
