name: 'Download elements build artifacts'
description: 'Download elements build artifacts that can be used by release workflows'
author: 'Benjamin Pagelsdorf'

runs:
  using: "composite"
  steps:
    - name: Download elements artifact
      uses: actions/download-artifact@v3
      with:
        name: elements
        path: packages/elements/dist/

    - name: Download elements-react artifact
      uses: actions/download-artifact@v3
      with:
        name: elements-react
        path: packages/elements-react/dist/

    - name: Download elements-angular artifact
      uses: actions/download-artifact@v3
      with:
        name: elements-angular
        path: packages/elements-angular/elements/dist/

    - name: Download elements-vue artifact
      uses: actions/download-artifact@v3
      with:
        name: elements-vue
        path: packages/elements-vue/dist/
