name: 'Upload elements build artifacts'
description: 'Upload elements build artifacts that can be used by release workflows'
author: 'Benjamin Pagelsdorf'

runs:
  using: "composite"
  steps:
  - name: Upload elements artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements
      path: packages/elements/dist/

  - name: Upload elements-react artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-react
      path: packages/elements-react/dist/

  - name: Upload elements-angular artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-angular
      path: packages/elements-angular/elements/dist/

  - name: Upload elements-vue artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-vue
      path: packages/elements-vue/dist/

  - name: Upload storybook artifact
    uses: actions/upload-artifact@v3
    with:
      name: storybook
      path: packages/storybook/dist/
