name: 'Upload elements build artifacts'
description: 'Upload elements build artifacts that can be used by release workflows'
author: 'Benjamin Pagelsdorf'

inputs:
  upload-core-artifacts:
    description: 'Upload core artifacts?'
    required: false
    default: 'false'
  upload-storybook-artifact:
    description: 'Upload storybook artifact?'
    required: false
    default: 'false'
  upload-example-artifacts:
    description: 'Upload example project artifacts?'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
  - if: inputs.upload-core-artifacts != 'false'
    name: Upload elements artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements
      path: packages/elements/dist/

  - if: inputs.upload-core-artifacts != 'false'
    name: Upload elements-react artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-react
      path: packages/elements-react/dist/

  - if: inputs.upload-core-artifacts != 'false'
    name: Upload elements-angular artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-angular
      path: packages/elements-angular/dist/

  - if: inputs.upload-core-artifacts != 'false'
    name: Upload elements-vue artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-vue
      path: packages/elements-vue/dist/

  - if: inputs.upload-storybook-artifact != 'false'
    name: Upload storybook artifact
    uses: actions/upload-artifact@v3
    with:
      name: storybook
      path: packages/storybook/dist/

  - if: inputs.upload-example-artifacts != 'false'
    name: Upload elements-angular-example artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-angular-example
      path: packages/elements-angular-example/dist/

  - if: inputs.upload-example-artifacts != 'false'
    name: Upload elements-react-example artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-react-example
      path: packages/elements-react-example/dist/

  - if: inputs.upload-example-artifacts != 'false'
    name: Upload elements-vue-example artifact
    uses: actions/upload-artifact@v3
    with:
      name: elements-vue-example
      path: packages/elements-vue-example/dist/
