/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface InoButton {
      'autofocus': boolean;
      'disabled': boolean;
      'form': string;
      'inoIconLeft': string;
      'inoIconRight': string;
      'inoSecondary': boolean;
      'name': string;
      'type': string;
    }
  }

  interface HTMLInoButtonElement extends StencilComponents.InoButton, HTMLStencilElement {}

  var HTMLInoButtonElement: {
    prototype: HTMLInoButtonElement;
    new (): HTMLInoButtonElement;
  };
  interface HTMLElementTagNameMap {
    'ino-button': HTMLInoButtonElement;
  }
  interface ElementTagNameMap {
    'ino-button': HTMLInoButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ino-button': JSXElements.InoButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface InoButtonAttributes extends HTMLAttributes {
      'autofocus'?: boolean;
      'disabled'?: boolean;
      'form'?: string;
      'inoIconLeft'?: string;
      'inoIconRight'?: string;
      'inoSecondary'?: boolean;
      'name'?: string;
      'type'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface InoIcon {
      'inoIcon': string;
    }
  }

  interface HTMLInoIconElement extends StencilComponents.InoIcon, HTMLStencilElement {}

  var HTMLInoIconElement: {
    prototype: HTMLInoIconElement;
    new (): HTMLInoIconElement;
  };
  interface HTMLElementTagNameMap {
    'ino-icon': HTMLInoIconElement;
  }
  interface ElementTagNameMap {
    'ino-icon': HTMLInoIconElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ino-icon': JSXElements.InoIconAttributes;
    }
  }
  namespace JSXElements {
    export interface InoIconAttributes extends HTMLAttributes {
      'inoIcon'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface InoInput {
      'accesskey': string;
      'autocomplete': string;
      'autofocus': boolean;
      'disabled': boolean;
      'max': string;
      'min': string;
      'name': string;
      'pattern': string;
      'placeholder': string;
      'required': boolean;
      'size': number;
      'tabindex': string;
      'type': string;
      'value': string;
    }
  }

  interface HTMLInoInputElement extends StencilComponents.InoInput, HTMLStencilElement {}

  var HTMLInoInputElement: {
    prototype: HTMLInoInputElement;
    new (): HTMLInoInputElement;
  };
  interface HTMLElementTagNameMap {
    'ino-input': HTMLInoInputElement;
  }
  interface ElementTagNameMap {
    'ino-input': HTMLInoInputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ino-input': JSXElements.InoInputAttributes;
    }
  }
  namespace JSXElements {
    export interface InoInputAttributes extends HTMLAttributes {
      'accesskey'?: string;
      'autocomplete'?: string;
      'autofocus'?: boolean;
      'disabled'?: boolean;
      'max'?: string;
      'min'?: string;
      'name'?: string;
      'pattern'?: string;
      'placeholder'?: string;
      'required'?: boolean;
      'size'?: number;
      'tabindex'?: string;
      'type'?: string;
      'value'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface InoSelect {
      'autofocus': boolean;
      'disabled': boolean;
      'form': string;
      'multiple': boolean;
      'name': string;
      'required': boolean;
      'size': number;
    }
  }

  interface HTMLInoSelectElement extends StencilComponents.InoSelect, HTMLStencilElement {}

  var HTMLInoSelectElement: {
    prototype: HTMLInoSelectElement;
    new (): HTMLInoSelectElement;
  };
  interface HTMLElementTagNameMap {
    'ino-select': HTMLInoSelectElement;
  }
  interface ElementTagNameMap {
    'ino-select': HTMLInoSelectElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ino-select': JSXElements.InoSelectAttributes;
    }
  }
  namespace JSXElements {
    export interface InoSelectAttributes extends HTMLAttributes {
      'autofocus'?: boolean;
      'disabled'?: boolean;
      'form'?: string;
      'multiple'?: boolean;
      'name'?: string;
      'required'?: boolean;
      'size'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StInput {
      'stAccesskey': string;
      'stAutocomplete': string;
      'stAutofocus': boolean;
      'stDisabled': boolean;
      'stForm': string;
      'stHasError': boolean;
      'stHelperText': string;
      'stIcon': string;
      'stMaxLength': number;
      'stMaxRows': number;
      'stMultiline': boolean;
      'stName': string;
      'stPlaceholder': string;
      'stRows': number;
      'stShowCounter': boolean;
      'stSpellcheck': boolean;
      'stTabindex': number;
      'stType': string;
      'stValue': string;
    }
  }

  interface HTMLStInputElement extends StencilComponents.StInput, HTMLStencilElement {}

  var HTMLStInputElement: {
    prototype: HTMLStInputElement;
    new (): HTMLStInputElement;
  };
  interface HTMLElementTagNameMap {
    'st-input': HTMLStInputElement;
  }
  interface ElementTagNameMap {
    'st-input': HTMLStInputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'st-input': JSXElements.StInputAttributes;
    }
  }
  namespace JSXElements {
    export interface StInputAttributes extends HTMLAttributes {
      'onChange'?: (event: CustomEvent) => void;
      'stAccesskey'?: string;
      'stAutocomplete'?: string;
      'stAutofocus'?: boolean;
      'stDisabled'?: boolean;
      'stForm'?: string;
      'stHasError'?: boolean;
      'stHelperText'?: string;
      'stIcon'?: string;
      'stMaxLength'?: number;
      'stMaxRows'?: number;
      'stMultiline'?: boolean;
      'stName'?: string;
      'stPlaceholder'?: string;
      'stRows'?: number;
      'stShowCounter'?: boolean;
      'stSpellcheck'?: boolean;
      'stTabindex'?: number;
      'stType'?: string;
      'stValue'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
