name: "Install node dependencies"
description: "Installs the node dependencies of inovex-elements packages"
author: 'Benjamin Pagelsdorf'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org
          scope: '@inovex.de' # important for yarn
          always-auth: true
    - name: restore lerna cache
      uses: actions/cache@v3
      id: lerna-cache
      with:
        path: **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
      shell: bash
