name: Deploy angular example

on:
  workflow_run:
    workflows: [ "Test & Build" ]
    types: [completed]
    branches: [elements-#653-deploy-example-projects]

jobs:
  deploy-elements-angular-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: elements-angular-example
          path: /example-projects/angular

      - name: Deploy Angular example project to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          commit-message: Deploying elements-angular-example
          clean-exclude: |
            version
            unicorn
