name: 'Prepare Release'

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/dependencies-install
        with:
          fetch-depth: 0
      - name: Bump version and create changelog
        run: lerna version
      - run: echo "elements_version=${jq -r .version package.json}" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: elements-release-${{ env.elements_version }}
          delete-branch: true
          labels: release
          base: master
          title: chore%3A publish v${{ env.elements_version }}
          body: ""
