name: Project Management

on:
  issues:
    types: [opened]

jobs:
  add_new_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Label "New"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            new
